import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Schema as MongooseSchema } from 'mongoose';

/**
 * PaymentMethod document type that combines the Mongoose document with the PaymentMethod schema.
 * This type is used to represent a MongoDB document in TypeScript.
 *
 * @export
 * @typedef {PaymentMethodDocument}
 */
export type PaymentMethodDocument = PaymentMethod & Document;

/**
 * Type definition for the `Status` field, representing the state of a payment method.
 * Currently, the only valid Status is `'ready_to_delete'`, but this can be expanded in the future.
 *
 * @typedef {Status}
 */
type Status = 'ready_to_delete';

/**
 * Schema for the PaymentMethod collection in MongoDB.
 * This schema stores various attributes related to a user's payment method.
 *
 * @export
 * @class PaymentMethod
 * @typedef {PaymentMethod}
 */
@Schema({ timestamps: true })
export class PaymentMethod {
  /**
   * Reference to the user who owns this payment method.
   * This is a required field that stores the user's ObjectId.
   *
   * @type {MongooseSchema.Types.ObjectId}
   */
  @Prop({ required: true, ref: 'User' })
  userId: MongooseSchema.Types.ObjectId;

  /**
   * Unique identifier for the payment method, provided by the payment gateway (e.g., Stripe, PayPal).
   * This field is required to identify the payment method in external systems.
   *
   * @type {string}
   */
  @Prop({ required: true })
  paymentMethodId: string;

  /**
   * The type of payment method (e.g., credit card, bank transfer, etc.).
   * This field is required and helps categorize the method used for payments.
   *
   * @type {string}
   */
  @Prop({ required: true })
  paymentMethod: string;

  /**
   * The country where the payment method was issued.
   * This can be useful for geographical and regulatory purposes.
   *
   * @type {string}
   */
  @Prop()
  country: string;

  /**
   * The expiration month of the payment method (for cards).
   * This field is optional and typically used with credit or debit cards.
   *
   * @type {number}
   */
  @Prop()
  exp_month: number;

  /**
   * The expiration year of the payment method (for cards).
   * This field is optional and typically used with credit or debit cards.
   *
   * @type {number}
   */
  @Prop()
  exp_year: number;

  /**
   * The unique fingerprint of the payment method, provided by the payment gateway.
   * It is used to detect duplicates or prevent fraud.
   *
   * @type {string}
   */
  @Prop()
  fingerprint: string;

  /**
   * Funding source for the payment method (e.g., credit, debit, prepaid).
   * This helps in understanding the type of financial product being used.
   *
   * @type {string}
   */
  @Prop()
  funding: string;

  /**
   * The last four digits of the payment card number.
   * This is typically used for displaying a masked version of the card number for user verification.
   *
   * @type {string}
   */
  @Prop()
  last4: string;

  /**
   * Metadata associated with the payment method.
   * This can store additional information as a key-value pair object.
   *
   * @type {object}
   */
  @Prop({ type: {} })
  metadata: object;

  /**
   * The name of the payment method owner.
   * This is typically the cardholder's name or the name associated with the payment method.
   *
   * @type {string}
   */
  @Prop()
  name: string;

  /**
   * Boolean flag to indicate whether this payment method is the default payment source.
   * Default sources are automatically used for transactions unless another method is specified.
   *
   * @type {boolean}
   */
  @Prop()
  is_default_source: boolean;

  /**
   * Status of the payment method, used to track its lifecycle.
   * For example, the status 'ready_to_delete' can be used to flag a payment method for deletion.
   * This field uses an enum to enforce valid values.
   *
   * @type {status}
   */
  @Prop({ type: String, enum: ['ready_to_delete'] })
  status: Status;

  @Prop({ default: false })
  isDeleted: boolean;

  @Prop({ default: null })
  deletedAt: Date;
}

/**
 * Mongoose schema for the PaymentMethod class.
 * This schema is generated by NestJS using the SchemaFactory, and it is used to interact with MongoDB.
 *
 * @type {MongooseSchema}
 */
export const PaymentMethodSchema = SchemaFactory.createForClass(PaymentMethod);
