#!/bin/bash

set -e

SERVICE="cms_api"

echo "Build ${SERVICE}:dev"
docker build --force-rm -f apps/cms-api/Dockerfile -t "${SERVICE}:dev" .

cd ../
echo "Deploy ${SERVICE}:dev"
docker-compose rm -s -f $SERVICE
docker-compose up -d $SERVICE
